
default: &default
  adapter: postgresql
  encoding: unicode
 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: photo_share_app_development


test:
  <<: *default
  database: photo_share_app_test


production:
  <<: *default
  database: photo_share_app_production
  username: photo_share_app
  password: <%= ENV['PHOTO_SHARE_APP_DATABASE_PASSWORD'] %>
